// /**
//  * Api Documentation
//  * Api Documentation
//  *
//  * OpenAPI spec version: 1.0
//  * 
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  * Do not edit the class manually.
//  */
// /* tslint:disable:no-unused-variable member-ordering */

// import { Inject, Injectable, Optional }                      from '@angular/core';
// import { HttpClient, HttpHeaders, HttpParams,
//          HttpResponse, HttpEvent }                           from '@angular/common/http';
// import { CustomHttpUrlEncodingCodec }                        from '../encoder';

// import { Observable }                                        from 'rxjs/Observable';

// import { ApiResponse } from '../model/apiResponse';
// import { Comment } from '../model/comment';
// import { CommentRequest } from '../model/commentRequest';
// import { PagedResponseOfComment } from '../model/pagedResponseOfComment';

// import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
// import { Configuration }                                     from '../configuration';


// @Injectable()
// export class CommentControllerService {

//     protected basePath = 'https://localhost:8080';
//     public defaultHeaders = new HttpHeaders();
//     public configuration = new Configuration();

//     constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
//         if (basePath) {
//             this.basePath = basePath;
//         }
//         if (configuration) {
//             this.configuration = configuration;
//             this.basePath = basePath || configuration.basePath || this.basePath;
//         }
//     }

//     /**
//      * @param consumes string[] mime-types
//      * @return true: consumes contains 'multipart/form-data', false: otherwise
//      */
//     private canConsumeForm(consumes: string[]): boolean {
//         const form = 'multipart/form-data';
//         for (const consume of consumes) {
//             if (form === consume) {
//                 return true;
//             }
//         }
//         return false;
//     }


//     /**
//      * addComment
//      * 
//      * @param commentRequest commentRequest
//      * @param postId postId
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public addCommentUsingPOST(commentRequest: CommentRequest, postId: number, observe?: 'body', reportProgress?: boolean): Observable<Comment>;
//     public addCommentUsingPOST(commentRequest: CommentRequest, postId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Comment>>;
//     public addCommentUsingPOST(commentRequest: CommentRequest, postId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Comment>>;
//     public addCommentUsingPOST(commentRequest: CommentRequest, postId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (commentRequest === null || commentRequest === undefined) {
//             throw new Error('Required parameter commentRequest was null or undefined when calling addCommentUsingPOST.');
//         }

//         if (postId === null || postId === undefined) {
//             throw new Error('Required parameter postId was null or undefined when calling addCommentUsingPOST.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];
//         const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
//         if (httpContentTypeSelected != undefined) {
//             headers = headers.set('Content-Type', httpContentTypeSelected);
//         }

//         return this.httpClient.post<Comment>(`${this.basePath}/api/posts/${encodeURIComponent(String(postId))}/comments`,
//             commentRequest,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * deleteComment
//      * 
//      * @param id id
//      * @param postId postId
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public deleteCommentUsingDELETE(id: number, postId: number, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
//     public deleteCommentUsingDELETE(id: number, postId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
//     public deleteCommentUsingDELETE(id: number, postId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
//     public deleteCommentUsingDELETE(id: number, postId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling deleteCommentUsingDELETE.');
//         }

//         if (postId === null || postId === undefined) {
//             throw new Error('Required parameter postId was null or undefined when calling deleteCommentUsingDELETE.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.delete<ApiResponse>(`${this.basePath}/api/posts/${encodeURIComponent(String(postId))}/comments/${encodeURIComponent(String(id))}`,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * getAllComments
//      * 
//      * @param postId postId
//      * @param page page
//      * @param size size
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public getAllCommentsUsingGET(postId: number, page?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<PagedResponseOfComment>;
//     public getAllCommentsUsingGET(postId: number, page?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagedResponseOfComment>>;
//     public getAllCommentsUsingGET(postId: number, page?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagedResponseOfComment>>;
//     public getAllCommentsUsingGET(postId: number, page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (postId === null || postId === undefined) {
//             throw new Error('Required parameter postId was null or undefined when calling getAllCommentsUsingGET.');
//         }



//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (page !== undefined && page !== null) {
//             queryParameters = queryParameters.set('page', <any>page);
//         }
//         if (size !== undefined && size !== null) {
//             queryParameters = queryParameters.set('size', <any>size);
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<PagedResponseOfComment>(`${this.basePath}/api/posts/${encodeURIComponent(String(postId))}/comments`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * getComment
//      * 
//      * @param id id
//      * @param postId postId
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public getCommentUsingGET(id: number, postId: number, observe?: 'body', reportProgress?: boolean): Observable<Comment>;
//     public getCommentUsingGET(id: number, postId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Comment>>;
//     public getCommentUsingGET(id: number, postId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Comment>>;
//     public getCommentUsingGET(id: number, postId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling getCommentUsingGET.');
//         }

//         if (postId === null || postId === undefined) {
//             throw new Error('Required parameter postId was null or undefined when calling getCommentUsingGET.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<Comment>(`${this.basePath}/api/posts/${encodeURIComponent(String(postId))}/comments/${encodeURIComponent(String(id))}`,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * updateComment
//      * 
//      * @param commentRequest commentRequest
//      * @param id id
//      * @param postId postId
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public updateCommentUsingPUT(commentRequest: CommentRequest, id: number, postId: number, observe?: 'body', reportProgress?: boolean): Observable<Comment>;
//     public updateCommentUsingPUT(commentRequest: CommentRequest, id: number, postId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Comment>>;
//     public updateCommentUsingPUT(commentRequest: CommentRequest, id: number, postId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Comment>>;
//     public updateCommentUsingPUT(commentRequest: CommentRequest, id: number, postId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (commentRequest === null || commentRequest === undefined) {
//             throw new Error('Required parameter commentRequest was null or undefined when calling updateCommentUsingPUT.');
//         }

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling updateCommentUsingPUT.');
//         }

//         if (postId === null || postId === undefined) {
//             throw new Error('Required parameter postId was null or undefined when calling updateCommentUsingPUT.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];
//         const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
//         if (httpContentTypeSelected != undefined) {
//             headers = headers.set('Content-Type', httpContentTypeSelected);
//         }

//         return this.httpClient.put<Comment>(`${this.basePath}/api/posts/${encodeURIComponent(String(postId))}/comments/${encodeURIComponent(String(id))}`,
//             commentRequest,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

// }
