/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Photo } from './photo';
import { User } from './user';


export interface AlbumRequest { 
    createdAt?: Date;
    createdBy?: number;
    id?: number;
    photo?: Array<Photo>;
    title?: string;
    updatedAt?: Date;
    updatedBy?: number;
    user?: User;
}
