/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InfoRequest { 
    bs?: string;
    catchPhrase?: string;
    city?: string;
    companyName?: string;
    lat?: string;
    lng?: string;
    phone?: string;
    street?: string;
    suite?: string;
    website?: string;
    zipcode?: string;
}
