/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Photo { 
    createdAt?: Date;
    createdBy?: number;
    id?: number;
    thumbnailUrl?: string;
    title?: string;
    updatedAt?: Date;
    updatedBy?: number;
    url?: string;
}
