/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Tag } from './tag';


export interface Post { 
    body?: string;
    category?: Category;
    createdAt?: Date;
    createdBy?: number;
    id?: number;
    tags?: Array<Tag>;
    title?: string;
    updatedAt?: Date;
    updatedBy?: number;
}
