/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Company } from './company';


export interface UserProfile { 
    address?: Address;
    company?: Company;
    email?: string;
    firstName?: string;
    id?: number;
    joinedAt?: Date;
    lastName?: string;
    phone?: string;
    postCount?: number;
    username?: string;
    website?: string;
}
