/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Company } from './company';
import { Role } from './role';


export interface User { 
    accessToken: string;
    address?: Address;
    company?: Company;
    createdAt?: Date;
    email?: string;
    firstName?: string;
    id?: number;
    lastName?: string;
    password?: string;
    phone?: string;
    roles?: Array<Role>;
    updatedAt?: Date;
    username?: string;
    website?: string;
}
